name: stocks
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.4
  - dash=1.20.0
  - scikit-learn=0.24.2
  - pyarrow==4.0.1 
  - xarray==0.18.2 
  - pip
  - pip:
    - streamlit==1.3.0
